In [1]:
from PIL import Image
from keras.applications.vgg16 import preprocess_input
import base64
from io import BytesIO
import json
import random
import cv2
from keras.models import load_model
import numpy as np

from keras.preprocessing import image

Using TensorFlow backend.


In [20]:
model = load_model('face_model_new_2.h5')

# Loading the cascades
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

In [21]:
def face_extractor(img):
    # Function detects faces and returns the cropped face
    # If no face detected, it returns the input image
    
    #gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(img, 1.3, 5)
    
    if faces is ():
        return None
    
    # Crop all faces found
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        cropped_face = img[y:y+h, x:x+w]

    return cropped_face

In [29]:
# Doing some Face Recognition with the webcam
video_capture = cv2.VideoCapture(0)

while True:
    _, frame = video_capture.read()
    #canvas = detect(gray, frame)
    #image, face =face_detector(frame)
    
    face=face_extractor(frame)
    if type(face) is np.ndarray:
        face = cv2.resize(face, (224, 224))
        im = Image.fromarray(face, 'RGB')
           #Resizing into 128x128 because we trained the model with this image size.
        img_array = np.array(im)
                    #Our keras model used a 4D tensor, (images x height x width x channel)
                    #So changing dimension 128x128x3 into 1x128x128x3 
        img_array = np.expand_dims(img_array, axis=0)
        pred = model.predict(img_array)
        print(pred)
                     
        name="None matching"
        
        if(pred[0][3]>0.5):
            name='Vishal'
        cv2.putText(frame,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    else:
        cv2.putText(frame,"No face found", (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    cv2.imshow('Video', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
        
video_capture.release()
cv2.destroyAllWindows()

[[0.000000e+00 0.000000e+00 0.000000e+00 1.000000e+00 3.008481e-25]]
[[0.0000000e+00 0.0000000e+00 0.0000000e+00 1.0000000e+00 9.3946634e-17]]
[[0.0000000e+00 0.0000000e+00 0.0000000e+00 1.0000000e+00 1.2343126e-11]]
[[0.0000000e+00 0.0000000e+00 0.0000000e+00 1.0000000e+00 2.8226484e-08]]
[[0.0000000e+00 9.8511053e-35 0.0000000e+00 1.0000000e+00 5.1584068e-17]]
[[0.0000000e+00 1.9829085e-26 0.0000000e+00 1.0000000e+00 1.4523784e-09]]
[[0.000000e+00 0.000000e+00 0.000000e+00 1.000000e+00 2.083109e-12]]
[[0.0000000e+00 0.0000000e+00 0.0000000e+00 1.0000000e+00 1.5868185e-11]]
[[0.         0.         0.         0.96157056 0.03842942]]
[[0.0000000e+00 2.7853808e-28 0.0000000e+00 1.0000000e+00 3.4561316e-16]]
[[0.         0.         0.         0.00212665 0.9978733 ]]
[[0.0000000e+00 0.0000000e+00 0.0000000e+00 9.9996901e-01 3.1019925e-05]]
[[0.0000000e+00 0.0000000e+00 0.0000000e+00 2.4170976e-13 1.0000000e+00]]
[[0.0000000e+00 0.0000000e+00 0.0000000e+00 1.0000000e+00 5.2014872e-08]]
[[0.